"""renamed column

Revision ID: 42df03c63dd8
Revises: ac6705717a74
Create Date: 2024-12-05 23:11:45.538711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42df03c63dd8'
down_revision = 'ac6705717a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('church', sa.String(length=150), nullable=True))
        batch_op.drop_index('contact')
        batch_op.create_unique_constraint(None, ['contact_number'])
        batch_op.drop_column('contact')
        batch_op.drop_column('church_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('church_number', mysql.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('contact', mysql.VARCHAR(length=10), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('contact', ['contact'], unique=True)
        batch_op.drop_column('church')
        batch_op.drop_column('contact_number')

    # ### end Alembic commands ###
