"""renamed column

Revision ID: ac6705717a74
Revises: 9407a27f2a16
Create Date: 2024-12-05 23:08:04.186540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac6705717a74'
down_revision = '9407a27f2a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('church_number', sa.String(length=150), nullable=True))
        batch_op.drop_column('church')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('church', mysql.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('church_number')

    # ### end Alembic commands ###
